### ISSUE TITLE
IO80211Family is missing from 10.13.6 to 10.15.7

### ISSUE THREAD

**Issue by 1alessandro1** [khronokernel/Apple-Kext-Clone#1]
Hi, thanks for this repo, I found it very useful to check whether a device-id is supported or not for a given WiFi card (or any device). 

I noticed that `IO80211Family.kext` is not present in HighSierra 10.13.6 to 10.15.7 System Extensions though, is this intentional?

**Comment by khronokernel** [comment]
They're not present on the BaseSystem, therefore wouldn't be in our repo

**Comment by 1alessandro1** [comment]
Ok, just for your information, I've installed every macOS version and the relative latest security update on a spare SSD and managed to copy all the extensions in SLE and LE and zip everything, the repository with IO80211 and everything else can be found here, I can share the missing files if you want

https://github.com/1alessandro1/Apple-Complete-Kext-Clone
